### ISSUE TITLE
Toolkit API documentation

### ISSUE THREAD

**Issue by rzschoch** [k-next/getkirby.com#82]
Are there any plans for a revised Kirby toolkit documentation? I’m using the toolkit methods quite often with Kirby 2 (https://getkirby.com/docs/toolkit/api).

**Comment by lukasbestle** [comment]
The framework docs are [already online](https://nnnnext.getkirby.com/docs/framework), but not linked to from anywhere. We had them in in the first version of the v3 site, but they turned out to be too overwhelming for new users, so we decided to hide them for now. But it's definitely something we will reconsider and improve after launch. Until then, you can get to the docs with the direct link.

**Comment by bastianallgeier** [comment]
The toolkit docs are now a part of the cheatsheet. They are not 100% complete yet, but will grow over time.
